steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/devfest/app:$BUILD_ID','./k8s-basics/.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/$PROJECT_ID/devfest/app:$BUILD_ID']
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
    - -n
    - demoapp
    - set
    - image
    - deployment
    - demoapp
    - demoapp=eu.gcr.io/$PROJECT_ID/devfest-demo/contacts:$BUILD_ID
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=pik-kube-workshop' 
