apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: demoapp
  labels:
    app: demoapp
    version: 1.0.0
spec: 
  replicas: 3
### Deployment rollout strategy
#  strategy:
#    type: RollingUpdate
#    rollingUpdate:
#      maxSurge: 1
#      maxUnavailable: 0
  selector:
    matchLabels:
      app: demoapp
  template: 
    metadata: 
      labels: 
        app: demoapp
    spec: 
      containers: 
      - name: demoapp
        image: kotrev/go-demo-app:1.0.0
        ports: 
          - containerPort: 8000
### ReadinessProbe
#        readinessProbe:
#          tcpSocket:
#            port: 8000
#          initialDelaySeconds: 10
#          periodSeconds: 10
### LifenessProbe
#        livenessProbe:
#          tcpSocket:
#            port: 8000
#          initialDelaySeconds: 15
#          periodSeconds: 20
### Resource management
#        resources:
#          requests:
#            cpu: 200m
#            memory: 128Mi
#          limits:
#            cpu: 300m
#            memory: 256Mi
### Pods assigment
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#            - matchExpressions:
#              - key: env
#                operator: In
#                values:
#                - dev
#          preferredDuringSchedulingIgnoredDuringExecution:
#          - weight: 1
#            preference:
#              matchExpressions:
#              - key: node-type
#                operator: In
#                values:
#                - preemptible
#        podAntiAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#          - labelSelector:
#              matchExpressions:
#              - key: app
#                operator: In
#                values:
#                - demoapp
#            topologyKey: "kubernetes.io/hostname"
#      tolerations:
#      - key: "env"
#        operator: "Equal"
#        value: "dev"
#        effect: "NoSchedule"
