apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    {{ if hasSuffix "-canary" .Release.Name }}
    track: canary
    {{ else }}
    track: stable
    {{ end }}
    heritage: {{ .Release.Service }}
  name: {{ template "app.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      {{ if hasSuffix "-canary" .Release.Name }}
      track: canary
      {{ else }}
      track: stable
      {{ end }}
      heritage: {{ .Release.Service }}
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        {{ if hasSuffix "-canary" .Release.Name }}
        track: canary
        {{ else }}
        track: stable
        {{ end }}       
        heritage: {{ .Release.Service }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ template "app.name" . }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
