{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "app.name" . }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: {{ template "app.name" . }}
  sessionAffinity: None
  type: {{ .Values.service.type }} 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "app.name" . }}
    track: stable
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "app.name" . }}-stable
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: {{ template "app.name" . }}
    track: stable
  sessionAffinity: None
  type: {{ .Values.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "app.name" . }}
    track: canary
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "app.name" . }}-canary
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: {{ template "app.name" . }}
    track: canary
  sessionAffinity: None
  type: {{ .Values.service.type }}
{{- end }}
